### ISSUE TITLE
[OoB_5.10]: Unable to import to online compiler.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-nfc#7] opened 2018-09-10 12:21 UTC
I'm unable to import the NFC repo into the online compiler. Screenshot below. I'm using the [partner beta online compiler](https://os-partnerbeta.mbed.com/compiler/#nav:/;) for OoB. cc: @donatieng @pan- ..

![nfc_onlinecompiler_import_error](https://user-images.githubusercontent.com/17567812/45297116-36443c80-b4fc-11e8-9def-56e7215a3edd.JPG)

**Comment by pan-** [comment] 2018-09-10 12:54
@ashok-rao I made the repository public, could you try again ?

**Comment by ashok-rao** [comment] 2018-09-10 13:08
@pan- , I can import fine, but it fails to compile now..I'm using 5.10.0-oob branch

![nfc_online_compiler_error](https://user-images.githubusercontent.com/17567812/45299272-f46ac480-b502-11e8-89a0-1a25d3d02838.JPG)

**Comment by adbridge** [comment] 2018-09-11 14:42
@pan- any progress on this ?

**Comment by pan-** [comment] 2018-09-11 15:33
@adbridge It looks like the online compiler is not able to pick up mbed-os-5.10, instead it picks up mbed-os-5.9.7. These issues are similar to https://github.com/ARMmbed/mbed-os-example-ble/issues/175 and https://github.com/ARMmbed/mbed-os-example-ble/issues/176 . 

Side note: That would be helpful to be able to report online compiler issues where they belongs.

**Comment by ashok-rao** [comment] 2018-09-11 17:29
@pan- .. I'm using 5.10.0 RC1 (in bold) in partner beta..but still it gives me build error as above.

![nfc_oc_version](https://user-images.githubusercontent.com/17567812/45376698-679e3480-b5f0-11e8-9094-454c2705d706.JPG)

**Comment by pan-** [comment] 2018-09-13 09:29
I'm closing this as this repo is not a tracker for web compiler issues. 

Please report to the web compiler project (https://github.com/ARMmbed/os.mbed.com/tree/master/mbed_compiler). If it is related to the layout of this project (very likely!) which is not web compiler friendly; it this won't change for this release.

**Comment by MarceloSalazar** [comment] 2018-09-13 13:08
This is the appropriate place to raise issues. 
@theotherjimmy @immunda can you please have a look?

**Comment by theotherjimmy** [comment] 2018-09-13 14:46
@MarceloSalazar, Vincent asked you to _track_ this on the online compiler repo, as this is not the appropriate place to _track_ this issue. This may be the appropriate place to _raise_ this issue, and now that we have looked into it, it seems unrelated to this particular project and that it should be _tracked_ where the bug is. Please do as he asks.

I can look into this, but as this may relate to projects that are not open source, I would have to restrict my reporting.

**Comment by ciarmcom** [comment] 2020-10-13 13:43
@ashok-rao thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment] 2020-10-18 13:25
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-23 13:25
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-28 14:25
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-04 17:44
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Closed** 2020-11-06 12:58 UTC
