### ISSUE TITLE
[OoB_5.10]: Smart Poster app.. what is expected?

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-nfc#8] opened 2018-09-10 12:28 UTC
After building the app with GCC_ARM and flashing to the device, on the serial terminal, the following output is seen:
```
Initialize: ret = 0
Start Discovery: ret = 0
Initiator discovered
Connected
Discovery terminated: 0
Disconnected
Initiator discovered
Connected
Discovery terminated: 0
Disconnected
Initiator discovered
Connected
Discovery terminated: 0
Disconnected
```

I'm not sure what is expected from the Android phone as nothing happens on the app and there is not enough documentation in the repo's README to show expected outcome.
cc @donatieng @pan- ..

**Comment by ashok-rao** [comment] 2018-09-10 13:14
Thanks @pan- .. I'm using the NXP TagInfo v4.23 from Play Store.. still does not open the webpage.. any recommendations?

**Comment by ashok-rao** [comment] 2018-09-11 10:00
@pan- .. I'm using a galaxy S5, Android 6..

**Comment by AnotherButler** [comment] 2018-09-11 21:00
@donatieng According to the OOB meeting notes, OOB is expecting screenshots, how to use the app and expected results. Are you able to add this content to this example?

**Comment by pan-** [comment] 2018-09-12 14:49
@ashok-rao This example works on the two Android phones available to me: Galaxy S7 Edge and Galaxy Note 3. However I noticed that sometimes binary wasn't correctly flashed on the dev board.

**Comment by ashok-rao** [comment] 2018-09-12 17:14
@pan- ..thanks. In that case, it might be an issue with the phone. I don't have access to an iOS device.. any chance you can double check with iOS as well? And as discussed earlier, could you please add steps to use the app and expected results to the docs? Thanks.

**Comment by ciarmcom** [comment] 2020-10-13 13:43
@ashok-rao thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment] 2020-10-18 13:25
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-23 13:25
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-28 14:25
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-04 17:44
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-09 18:10
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-14 21:19
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-19 21:20
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-25 06:24
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-30 06:24
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-12-05 08:23
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-12-10 08:24
@ashok-rao it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by paul-szczepanek-arm** [comment] 2020-12-10 14:16
It works on all the phones I have. Cannot reproduce and since Ashok isn't here anymore to verify I am closing this.

**Closed by paul-szczepanek-arm** 2020-12-10 14:16 UTC
